### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED / CERTIFICATE HAS EXPIRED

### ISSUE THREAD

**Issue by dids-reyes** [Viralmaniar/SMWYG-Show-Me-What-You-Got#10]
Exceptions Occured: Pointing to SSL Certificate and HTTPS 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)
```

**Comment by BenjaminSou** [comment]
This is due to https://gotcha.pw/ having no more HTTPS Certificates, thus connection is unusable.

`HTTPSConnectionPool(host='gotcha.pw', port=443): Max retries exceeded with url: /search/uber.com (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))`

**Comment by joeyagreco** [comment]
A possible solution to this would be refactoring to use the [Have I Been Pwned API](https://haveibeenpwned.com/API/v3)
