### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by Doujinx** [Viralmaniar/SMWYG-Show-Me-What-You-Got#12]
[+] Checking Internet connection...
[+] Connection Successful <3 <3 <3

1. Enter Domain Name to Search Users
2. Enter Specific Email Address
3. Exit
1
Enter Domain Name:facebook.com

```
Traceback (most recent call last):
  File "/home/kali/Programs/PROJECT HACKINGTOOL/WordlistGenerator/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 115, in <module>
    main()
  File "/home/kali/Programs/PROJECT HACKINGTOOL/WordlistGenerator/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 106, in main
    cmds.get(choice)()
  File "/home/kali/Programs/PROJECT HACKINGTOOL/WordlistGenerator/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 75, in cmdDomainSearch
    print (div.get_text())
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'

```

**Comment by ghost** [comment]
gotch.pw (the database) is gone, but someone took the domain name after the database was shut down, hence you see "connection successful" even though the script doesn't work
