### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Bermandre** [Viralmaniar/SMWYG-Show-Me-What-You-Got#13]
Traceback (most recent call last):
  File "/root/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 115, in <module>
    main()
  File "/root/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 106, in main
    cmds.get(choice)()
  File "/root/SMWYG-Show-Me-What-You-Got/SMWYG.py", line 75, in cmdDomainSearch
    print (div.get_text())
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by Steffano198** [comment]
isnt working anymore, gotcha.pw is down, that is the database
