### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by joker2a** [Viralmaniar/SMWYG-Show-Me-What-You-Got#2]
Hi,

I have an error with kali linux

Output =

python3 SMWYG.py

        ___          
    . -^   `--,      
   /# =========`-_   
  /# (--====___====\ 
 /#   .- --.  . --.| 
/##   |  * ) (   * ),           +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|##   \    /\ \   / |           |S|h|o|w|M|e|W|h|a|t|Y|o|u|G|o|t|
|###   ---   \ ---  |           +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|####      ___)    #|                   Author: Viral Maniar
|######           ##|                   Twitter: @ManiarViral
 \##### ---------- /                    Description: This tool allows you to perform OSINT and reconnaissance on an organization or an individual. It allows one to search 1.4 Billion 
  \####           (                             clear text credentials which was dumped as part of BreachCompilation leak. 
   `\###          |  
     \###         |  
      \##        |   
       \###.    .)   
        `======/     
         ***1.4 Billion Clear Text Credentials***
 
[+] Checking Internet connection...
[+] Connection Successful <3 <3 <3

1. Enter Domain Name to Search Users
2. Enter Specific Email Address
3. Exit
1   
Enter Domain Name:uber.com
Traceback (most recent call last):
  File "SMWYG.py", line 115, in <module>
    main()
  File "SMWYG.py", line 106, in main
    cmds.get(choice)()
  File "SMWYG.py", line 75, in cmdDomainSearch
    print (div.get_text())
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by R4di04kt1v3** [comment]
That happens to me too.

**Comment by Museon23** [comment]
same thing ^, thanks.

> 1. Enter Domain Name to Search Users
>2. Enter Specific Email Address
>3. Exit
>1
>Enter Domain Name:uber.com
>Traceback (most recent call last):
> File "SMWYG.py", line 115, in <module>
>   main()
> File "SMWYG.py", line 106, in main
>   cmds.get(choice)()
> File "SMWYG.py", line 75, in cmdDomainSearch
>    print (div.get_text())
>AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by moas** [comment]
gotcha.pw is Down (it's the reason)!

**Comment by Bobavince** [comment]
same (of course)
